stages:
  - build
  - deploy

build webstore:
  stage: build
  image: node:11-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - webstore
  variables:
    api: localhost/api
  script:
    - yarn install
    - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod

deploy webstore:
  stage: deploy
  tags:
    - webstore
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/frontend/. ~/front-deployment
