stages:
  - package
  - deploy

before_script:
  - export APP_CONTAINER_NAME=webstore-front-container
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN

package webstore:
  stage: package
  tags:
    - webstore
  script:
    - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_REPOSITORY:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_USER/$CI_REGISTRY_REPOSITORY


deploy webstore:
  stage: deploy
  tags:
    - webstore
  script:
    - bash ./scripts/deploy.sh
