stages:
  - build
  - package
  - deploy

before_script:
  - export APP_CONTAINER_NAME=webstore-front-container
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN

build webstore:
  stage: build
  image: node:11-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - webstore
  variables:
    api: localhost/api
  script:
    - yarn install
    - cat ./deploy/angular/proxy.conf.json > ./proxy.conf.json
    - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod
  only:
    - master
    - tags

package webstore:
  stage: package
  tags:
    - webstore
  script:
    - bash ./scripts/package.sh
  only:
    - master
    - tags

deploy webstore:
  stage: deploy
  tags:
    - webstore
  script:
    - ssh -i ~/.ssh/id_deploy $CI_DEPLOY_USER@$CI_DEPLOY_SERVER env CI_REGISTRY_USER=$CI_REGISTRY_USER CI_REGISTRY_REPOSITORY=$CI_REGISTRY_REPOSITORY CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA APP_CONTAINER_NAME=$APP_CONTAINER_NAME 'bash -s' < ./scripts/deploy.sh
  only:
    - master
    - tags
